export const API_ERRORS_MESSAGE = {
    1: "Enseigne invalide",
    2: "Numéro d'enseigne vide ou inexistant",
    3: "Numéro de compte enseigne invalide",
    5: "Numéro de dossier enseigne invalide",
    7: "Numéro de client enseigne invalide",
    8: "Mot de passe ou hachage invalide",
    9: "Ville non reconnu ou non unique",
    10: "Type de collecte invalide",
    11: "Numéro de Relais de Collecte invalide",
    12: "Pays de Relais de collecte invalide",
    13: "Type de livraison invalide",
    14: "Numéro de Relais de livraison invalide",
    15: "Pays de Relais de livraison invalide",
    20: "Poids du colis invalide",
    21: "Taille (Longueur + Hauteur) du colis invalide",
    22: "Taille du Colis invalide",
    26: "Temps de montage invalide",
    27: "Mode de collecte ou de livraison invalide",
    28: "Mode de collecte invalide",
    29: "Mode de livraison invalide",
    30: "Adresse (L1) invalide",
    31: "Adresse (L2) invalide",
    33: "Adresse (L3) invalide",
    34: "Adresse (L4) invalide",
    35: "Ville invalide",
    36: "Code postal invalide",
    37: "Pays invalide",
    38: "Numéro de téléphone invalide, modifier le numéro sur l'adresse de l'expédition (il peut manquer un '+')",
    39: "Adresse e-mail invalide",
    40: "Paramètres manquants",
    42: "Montant CRT invalide",
    43: "Devise CRT invalide",
    44: "Valeur du colis invalide",
    45: "Devise de la valeur du colis invalide",
    46: "Plage de numéro d'expédition épuisée",
    47: "Nombre de colis invalide",
    48: "Multi-Colis Relais Interdit",
    49: "Action invalide",
    60: "Champ texte libre invalide (Ce code erreur n'est pas invalidant)",
    61: "Top avisage invalide",
    62: "Instruction de livraison invalide",
    63: "Assurance invalide",
    64: "Temps de montage invalide",
    65: "Top rendez-vous invalide",
    66: "Top reprise invalide",
    67: "Latitude invalide",
    68: "Longitude invalide",
    69: "Code Enseigne invalide",
    71: "Nature de point de vente non valide",
    74: "Langue invalide",
    78: "Pays de Collecte invalide",
    79: "Pays de Livraison invalide",
    93: "Aucun élément retourné par le plan de tri Si vous effectuez une collecte ou une livraison en Point Relais, vérifiez que les Point Relais sont bien disponibles. Si vous effectuez une livraison à domicile, il est probable que le code postal que vous avez indiqué n'existe pas.",
    94: "Colis Inexistant",
    95: "Compte Enseigne non activé",
    96: "Type d'enseigne incorrect en Base",
    97: "Clé de sécurité invalide Cf. : § « Génération de la clé de sécurité »",
    98: "Erreur générique (Paramètres invalides) Cette erreur masque une autre erreur de la liste et ne peut se produire que dans le cas où le compte utilisé est en mode « Production ». Cf. : § « Fonctionnement normal et debugage »",
    99: "Erreur générique du service Cette erreur peut être due à un problème technique du service. Veuillez notifier cette erreur à Mondial Relay en précisant la date et l'heure de la requête ainsi que les paramètres envoyés afin d'effectuer une vérification.",
};
